name:                csg
version:             0.1.0.0
github:              "githubuser/csg"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/csg#readme>

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveAnyClass
  - DeriveTraversable
  - DerivingVia
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - RecursiveDo
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances

dependencies:
- QuickCheck
- aeson
- array
- attoparsec
- base
- bytestring
- containers
- criterion
- deepseq
- hspec
- integer-roots
- optparse-applicative
- pretty
- pretty-show
- random
- text
- time
- vector
- yaml

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -dumpdir "dump"
  - -ddump-to-file
  # - -ddump-prep
  # - -ddump-stg-final

executables:
  csg-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - csg

  # csg-bench:
    # main:                Bench.hs
    # source-dirs:         bench
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    # dependencies:
    # - csg

tests:
  csg-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - csg
